#!/bin/bash -eu

readonly bazel_platform="darwin"
readonly tulsi_script="tools/tulsiw"

if [[ ! -d $1 ]]; then
  echo "$0 must be run from the BazelSample directory"
  exit 1
fi

exec "${tulsi_script}" --bazel $(which bazel) \
    --genconfig "$1:$2"